### PR TITLE
Update chapter 2 to use secrets.exs for Binance config

### PR DESCRIPTION
**Pull request by mcintyre94**
See related book PR: https://github.com/frathon/hands-on-elixir-and-otp-cryptocurrency-trading-bot/pull/16

### CODE REVIEW

**Comment by Cinderella-Man** [comment]
Hi @mcintyre94 

Thank you for your PR, I think the `config/secrets.exs` file should not be added to it as if it's there people will modify it and in the end, it will end up in the repository - we wanted to avoid that :wink: ?

**Comment by mcintyre94** [comment]
Ah agreed, I didn't realise that changes to an ignored file got added by default after it was force added once! Thought you had to `git add --force` to update and that'd be enough to avoid people changing it. Will remove it, thanks!

**Comment by mcintyre94** [comment]
Fixed! :)

**Comment by Cinderella-Man** [comment]
As per my comment in the other PR - thank you very much and congrats on becoming a contributor :rocket: :heart:

**Comment by Cinderella-Man** [comment]
Hmmm, I just realized - is there any reason why you used single quotes instead of double quotes in both the book and the snippet? :thinking:

**Comment by mcintyre94** [comment]
Not particularly, I'm pretty un-opinionated about single vs double TBH. `mix format` doesn't seem to change either one. Probably would make more sense to use doubles though since that's what you used throughout. Want me to open a PR to change them over?

**Comment by Cinderella-Man** [comment]
Yeah, double quotes are a safe bet as this is what docs are suggesting - I will update both myself, no problemo :wink:  just wanted to make sure that I'm no missing anything

**Comment by Cinderella-Man** [comment]
Sorry for spamming this PR - all branches are now updated :wink:

**Pull request merged**
