### PR TITLE
Fix/chapter 21

### PR DESCRIPTION
**Pull request by lucca65**

### CODE REVIEW

**Comment by Cinderella-Man** [comment]
Hey :wave: 

I wonder what you were trying to do - please let me know if you found anything - thanks in advance!

PS. Please avoid looking into chapter_21 branch because I'm still working on it - apologies if that wasn't clear, but the book at this moment officially cuts off at the 20th chapter.

Have a great weekend

**Comment by lucca65** [comment]
Hey @Cinderella-Man! Sorry I accidentally open the PR on the main repo instead of our fork!

I'm using your project to fiddle around with some implementations of trading algorithms and was doing the necessary work to make it work with my context. This is just for study and exploration for now and you can follow it on our fork! Hopefully we do something that is useful to the book implementation! https://github.com/cambiatus/hands-on-elixir-and-otp-cryptocurrency-trading-bot-source-code/pull/1/files

I guess you talked to one of our peers Ranulfo as well!

**Comment by Cinderella-Man** [comment]
Hey @lucca65 

No problem at all. I hope the crypto bot code will be helpful in your research. Thank you very much for sharing the repo/PR - I will follow your fork closely for inspiration :wink: 


Yes, I had the pleasure to meet Ranulfo and Karla briefly - best of luck with your initiative! :rocket:

**Comment by lucca65** [comment]
Thanks for the work and book @Cinderella-Man! its been useful to learn!

**Pull request closed without merging**
